### ISSUE TITLE
Separate repository for backend

### ISSUE THREAD

**Issue by Morosko** [jflesch/paperwork-backend#1]
Is there a certain reason why the backend was split into a separate repository?
How do you handle the two repositories in one directory? 

In my opinion it would make much more sense to put everything in different branches which brings the following benefits:
- easier workflow with git itself
- easier to release in stable branch with simple merging
- easier testing

**Comment by jflesch** [comment]
I'm not sure to understand what you suggest.
You mean having both in the same repository, but the frontend in a branch "unstable-frontend", and the backend in a branch "unstable-backend" ?

**Comment by Morosko** [comment]
Yeah, you got it right.

**Comment by jflesch** [comment]
You can do that easily on your side if you like:
- clone one of the repo
- use ```git remote add``` to add the other one
- git pull

You end up with a very similar result. (that's what I'm doing to cherry-pick commits from the branch stable that belongs to the backend)

And actually, I find it really dirty to have 2 branches with totally different content in a same repository. I know of no one using Git that way.

For me, there is only 2 clean choices for this split:
- 2 subdirectories in a same repository+branch. Meaning they share their history and tags, which means they should be released together
- 2 repositories.

Also, the rational behind this split:
- people want to build other GUI on top of the backend. 
- I may need to be able to release updates for the backend without releasing the changes in the frontend. I may also need to update the frontend without making a new release of the backend.
- I want to make clear both should be packaged separately
- There is no reason for them to share a common history. Backend should be independent from the frontend, and so its history should be.

**Comment by Morosko** [comment]
Ok, those are some good reasons and answers to my questions. Thanks

**Comment by jflesch** [comment]
You're welcome :)
